CC = g++ # compiler on linux

all: toaster.cpp # requires .cpp file
	@$(CC) toaster.cpp -o toaster # compiled C++ program is toaster. @ will suppress the echo

run: all
	@./toaster # compiles the program and runs it program

clean:
	@rm -rf toaster # clears the output
