CC = g++ # compiler on linux

all: oeecalculator.cpp # requires .cpp file
	@$(CC) oeecalculator.cpp -o oeecalculator # compiled C++ program is oeecalculator. @ will suppress the echo

run: all
	@./oeecalculator 420 47 0.016666667 18848 19271 # compiles the program and runs it

clean:
	@rm -rf oeecalculator # clears the output