CC = g++ # compiler on linux

all: sudokusolver.cpp # requires .cpp file
	@$(CC) sudokusolver.cpp -o sudokusolver # compiled C++ program is sudokusolver. @ will suppress the echo

run: all
	@./sudokusolver # compiles the program and runs it program

clean:
	@rm -rf sudokusolver # clears the output