CC = g++ # compiler on linux

all: FizzBuzz.cpp # requires .cpp file
	@$(CC) FizzBuzz.cpp -o FizzBuzz # compiled C++ program is FizzBuzz. @ will suppress the echo

run: all
	@./FizzBuzz # compiles the program and runs it program

clean:
	@rm -rf FizzBuzz # clears the output